---

- name: "Clone chloroplast git repo"
  git:
      repo: https://github.com/sparthaje/chlorophyll
      dest: ~/chlorophyll
      force: yes

- name: "Create virtual environment"
  shell: "cd ~/chlorophyll && python3 -m venv venv"

- name: "Install required pip packages for chloroplast"
  shell: "cd ~/chlorophyll && source venv/bin/activate && cd chloroplast && pip install -r requirements.txt"

- name: "Install required pip packages for chloroplast"
  shell: "cd ~/chlorophyll && source venv/bin/activate && cd chloroplast && pip install -r requirements.txt"

- name: "Install required pip packages for shortcut-tool"
  shell: "cd ~/chlorophyll && source venv/bin/activate && cd shortcut_tool && pip install -r requirements.txt"

- name: "firebase.secret to chloroplast"
  copy:
    src: "files/firebase.secret"
    dest: "~/chlorophyll/chloroplast/firebase.secret"

- name: "databaseurl.secret to chloroplast"
  copy:
    src: "files/databaseurl.secret"
    dest: "~/chlorophyll/chloroplast/databaseurl.secret"

- name: "firebase.secret to shortcut_tool"
  copy:
    src: "files/firebase.secret"
    dest: "~/chlorophyll/shortcut_tool/firebase.secret"

- name: "databaseurl.secret to shortcut_tool"
  copy:
    src: "files/databaseurl.secret"
    dest: "~/chlorophyll/shortcut_tool/databaseurl.secret"
