---

- name: Install aptitude
  apt:
    name: aptitude
    state: present

- name: Update apt packages
  apt:
    update_cache: yes
  tags:
    - general

- name: Install necessary packages
  apt: 
    name: "{{item}}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3-pip
    - python3-venv
    - vim
    - git
    - htop
  tags:
    - general

