---

- name: Load Chloroplast Docker
  shell: "docker load < ~/dockerimages/chloroplast-docker.tar"

- name: Load Solar Docker
  shell: "docker load < ~/dockerimages/solar-docker.tar"

- name: Load cwatchme Docker
  shell: "docker load < ~/dockerimages/c-watchdog-docker.tar"
